### ISSUE TITLE
Final Answer key released, Add the Final Ans key values

### ISSUE THREAD

**Issue by Quantum-HG** [nikhilmwarrier/jee-2024-scraper#18]
[final.pdf](https://github.com/nikhilmwarrier/jee-2024-scraper/files/14236482/final.pdf)

**Comment by AshutoshGitMirror** [comment]
+1 @nikhilmwarrier

**Comment by AshutoshGitMirror** [comment]
lagta hai developer result dekh kar mar gya abhi tak issue nahi dekha /s

**Comment by Quantum-HG** [comment]
> lagta hai developer result dekh kar mar gya abhi tak issue nahi dekha /s

Ha bhai

**Comment by nikhilmwarrier** [comment]
Added for April session.
