### ISSUE TITLE
Issue with key for 31st January Shift 1 (31s1.json)

### ISSUE THREAD

**Issue by MineRock** [nikhilmwarrier/jee-2024-scraper#6]
Unlike the rest of the answer keys, 31s1 just has the question ID and the corresponding question number from the user who submitted the answer key I assume. Could you look into that? Thanks a lot for the script, great work!

**Comment by nikhilmwarrier** [comment]
Oh yes you are right. I'll update that.

**Comment by nikhilmwarrier** [comment]
Fixed in [b39a399](https://github.com/nikhilmwarrier/jee-2024-scraper/commit/b39a3992f343b4398f8c2f8e2567da0dace44401)
